version: '2'
services:
    spring-rest-elasticsearch-6.0.0:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "xpack.security.enabled=false"
            - "cluster.name=elasticsearch"
